apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: gitops-finops-showcase
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: gitops-finops-showcase
    spec:
      containers:
        - name: api-service
          image: hashicorp/http-echo:latest
          args:
            - "-text=API Service Response - GitOps-FinOps Showcase"
            - "-listen=:8080"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
