apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    environment: platform
    team: platform
    cost-center: shared-overhead
    owner: platform-team
    kubernetes.io/metadata.name: ingress-system
