apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api-service-dev
namePrefix: dev-
resources:
- namespace.yaml
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: dev
    cost-center: agency-rnd
    owner: agency-internal
    team: platform
patches:
- target:
    kind: Deployment
    name: api-service
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
