apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubecost

resources:
  - kubecost-rendered.yaml

commonLabels:
  app.kubernetes.io/part-of: kubecost
  app.kubernetes.io/managed-by: argocd
