apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app-dev
namePrefix: dev-
resources:
- namespace.yaml
- ../../base
# Labels applied to all resources in this overlay
# Images - Argo CD Image Updater will modify this
images:
- name: ghcr.io/RadiantKnightLLC/showcase-app-p1
  newName: nginx
  newTag: alpine
labels:
- includeSelectors: true
  pairs:
    cost-center: agency-rnd
    environment: dev
    owner: agency-internal
    team: platform
patches:
- path: labels.yaml
- path: patches.yaml

