apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app-dev
namePrefix: dev-
resources:
- namespace.yaml
- nginx-config.yaml
- ../../base
# Labels applied to all resources in this overlay
# Images - Argo CD Image Updater will modify this
# Using containerized showcase-app-p1 (React Tic-Tac-Toe)
labels:
- includeSelectors: true
  pairs:
    cost-center: agency-rnd
    environment: dev
    owner: agency-internal
    team: platform
patches:
- path: labels.yaml
- path: service-patch.yaml
- path: deployment-patch.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: sample-app

