apiVersion: v1
kind: Namespace
metadata:
  name: sample-app-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    # Cost allocation metadata
    kubecost_cost_allocation: "enabled"
  labels:
    # Namespace-level labels for cost attribution
    environment: dev
    team: platform
    cost-center: agency-rnd
    owner: agency-internal
    # Kubernetes recommended labels
    kubernetes.io/metadata.name: sample-app-dev
    pod-security.kubernetes.io/enforce: privileged
