apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: gitops-finops-showcase
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: sample-app
