apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/RadiantKnightLLC/gitops-cost-showcase.git
        revision: master
        directories:
          - path: apps/api-service/overlays/*
  template:
    metadata:
      name: 'api-service-{{ .path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/RadiantKnightLLC/gitops-cost-showcase.git
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'api-service-{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
